[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Physical Computing HAWK"
authors = [{name = "JLK", email = "jasper.kuehn@hawk.de"}]
dynamic = ["version", "description"]
